apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "playout.fullname" . }}
  labels:
    {{- include "playout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  selector:
    matchLabels:
      {{- include "playout.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
      partition: {{ .Values.updateStrategy.rollingUpdate.partition }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "playout.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.env }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.timezone.enabled }}
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        {{- end }}
      {{- if .Values.timezone.enabled }}
      volumes:
      - name: tz-config
        hostPath:
          path: {{ .Values.timezone.path }}
          type: File
      {{- end }}
